// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnvvbijaqbxfuodsrqup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1udnZiaWphcWJ4ZnVvZHNycXVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5ODkyODUsImV4cCI6MjA2MzU2NTI4NX0.JsEg-M2sB9p3hVN3h4p-h6j9wQMuhx0P6aW41LtvC1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);